name: Security hardening (Github Actions workflows)

on:
  pull_request:
    types: [opened, synchronize]
    paths: [".github/workflows/**"]

jobs:
  ci_harden_security:
    uses: xunleii/github-actions-grimoire/.github/workflows/security.workflows.yaml@main # NOTE: always uses latest revision for testing purpose
