name: Security hardening (Github Actions workflows) - Spell

on:
  workflow_call:

jobs:
  # CI harden security tries to keep your github actions secure by following these simple rules:
  # - Ensure that all action and reusable workflow are pinned using directly a commit SHA
  # - Check if no issues are found on your Javascript and Python scripts using CodeQL
  ci_harden_security:
    name: Github Action security hardening
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4

      - name: Ensure SHA pinned actions
        uses: xunleii/github-actions-ensure-sha-pinned-actions@2eaa0713ff409846b288063c9d2d3b74577aab95 # NOTE: use forked action waiting

      - name: Initialize CodeQL
        uses: github/codeql-action/init@1b37538d9c22dd3f3d0c52992fa20da98683bd34 # renovate: tag=v1.0.15
        with:
          languages: javascript, python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@1b37538d9c22dd3f3d0c52992fa20da98683bd34 # renovate: tag=v1.0.15
        with:
          checkout_path: ${{ github.workspace }}/.github/workflows
