name: Security hardening (Github Actions workflows)

on:
  pull_request:
    types: [opened, synchronize]
    paths: [".github/workflows/**"]

jobs:
  ci_harden_security:
    uses: xunleii/github-actions-grimoire/.github/workflows/security.workflows.yaml@6970f1c497d58e9a44a5dd3fc796a7559f626cca
