name: Iaas - Terraform CI (for pull requests)

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      # if fixtures are updated
      - fixtures/terraform/**.tf
      - fixtures/terraform/**/.terraform.lock.hcl

      # if workflows are updated
      - .github/workflows/terraform.pull_requests.yaml
      - .github/workflows/zzz_run.terraform.pull_requests.yaml

jobs:
  tf_project_01-lint:
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.lint.yaml@a24b366e504f9166cbaec96a4d516903739ec677
    with:
      terraform_workdir: fixtures/terraform/project-01
  tf_project_01-plan:
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.plan.yaml@a24b366e504f9166cbaec96a4d516903739ec677
    with:
      terraform_workdir: fixtures/terraform/project-01
      terraform_vars: |
        var: ...
    secrets:
      terraform_vars: |
        secret: '***'

  tf_project_02-plan:
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.plan.yaml@a24b366e504f9166cbaec96a4d516903739ec677
    with:
      after_lint: false
      terraform_workdir: fixtures/terraform/project-02
      terraform_vars: |
        var: ...
    secrets:
      terraform_vars: |
        secret: '***'
